# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://43.202.89.97:55936/harmonimo # Database이름 ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: 0208
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  # 문서 접속 URL 변경 (접속시 /swagger-ui/index.html 로 redirect됨)
  springdoc.swagger-ui.path: /api-document.html

  # 캐시 비활성화 (Swagger 구성 요소중 캐시로 처리되는 부분이 있음, 로컬 환경에서만 사용하는 것이 좋을듯)
  springdoc.cache.disabled: true

  # 모든 @ControllerAdvice 응답이 모든 api의 응답으로 추가됨 (모든 응답에 추가되므로, 해당 response가 일어나지 않는 api에도 추가가 됨. false로 설정)
  springdoc.override-with-generic-response: false
